### ISSUE TITLE
requirements for spglib version

### ISSUE THREAD

**Issue by stepan-tsirkin** [irreducible-representations/irrep#79]
Hi, with spglibb-2.4.0 I get an error 
```
Traceback (most recent call last):
  File "/home/stepan/github/wannirrep/example-dwann/pw_inputs/gen-Dwann.py", line 3, in <module>
    bandstructure = BandStructure(prefix="di",
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stepan/github/wannirrep/irrep/irrep/bandstructure.py", line 240, in __init__
    self.spacegroup = SpaceGroup(
                      ^^^^^^^^^^^
  File "/home/stepan/github/wannirrep/irrep/irrep/spacegroup.py", line 574, in __init__
    shiftUC_tmp) = self._findsym(cell, from_sym_file, alat)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stepan/github/wannirrep/irrep/irrep/spacegroup.py", line 672, in _findsym
    rotations = dataset.rotations
                ^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'rotations'
```

With latest (spglib-2.5.0) it works fine. I think we may just update the requirement for spglib>=2.5.0, and not bother supporting older versions. Currently the requirement is very old

https://github.com/irreducible-representations/irrep/blob/4a1b4862929cc16151567a86d4f6b6a5a02b851a/setup.py#L15-L16

Also, maybe look at other requirements if we need to update them.

**Comment by MIraola** [comment]
I have  opened the PR #80  to fix this. It is ready to merge.
